// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

void ui_TelaInicial_screen_init(void)
{
    ui_TelaInicial = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_TelaInicial, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_btnTipoFilamento = lv_btn_create(ui_TelaInicial);
    lv_obj_set_width(ui_btnTipoFilamento, 200);
    lv_obj_set_height(ui_btnTipoFilamento, 100);
    lv_obj_set_x(ui_btnTipoFilamento, 0);
    lv_obj_set_y(ui_btnTipoFilamento, 25);
    lv_obj_set_align(ui_btnTipoFilamento, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_btnTipoFilamento, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_btnTipoFilamento, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_btnTipoFilamento, lv_color_hex(0x0E603B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnTipoFilamento, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labelTextoBotaoFilamento = lv_label_create(ui_btnTipoFilamento);
    lv_obj_set_width(ui_labelTextoBotaoFilamento, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelTextoBotaoFilamento, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_labelTextoBotaoFilamento, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelTextoBotaoFilamento, "PLA");
    lv_obj_set_style_text_font(ui_labelTextoBotaoFilamento, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labelTime = lv_label_create(ui_TelaInicial);
    lv_obj_set_width(ui_labelTime, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelTime, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labelTime, 32);
    lv_obj_set_y(ui_labelTime, -4);
    lv_obj_set_align(ui_labelTime, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelTime, "5");
    lv_obj_set_style_text_font(ui_labelTime, &lv_font_montserrat_40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labelTemp = lv_label_create(ui_TelaInicial);
    lv_obj_set_width(ui_labelTemp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelTemp, LV_SIZE_CONTENT);    /// 2
    lv_obj_set_x(ui_labelTemp, -59);
    lv_obj_set_y(ui_labelTemp, -4);
    lv_obj_set_align(ui_labelTemp, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelTemp, "55");
    lv_obj_set_style_text_font(ui_labelTemp, &lv_font_montserrat_40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_bStart = lv_btn_create(ui_TelaInicial);
    lv_obj_set_width(ui_bStart, 192);
    lv_obj_set_height(ui_bStart, 89);
    lv_obj_set_x(ui_bStart, -1);
    lv_obj_set_y(ui_bStart, 89);
    lv_obj_set_align(ui_bStart, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_bStart, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_bStart, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label4 = lv_label_create(ui_bStart);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "INICIAR");
    lv_obj_set_style_text_font(ui_Label4, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image1 = lv_img_create(ui_TelaInicial);
    lv_img_set_src(ui_Image1, &ui_img_thermometer_png);
    lv_obj_set_width(ui_Image1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image1, -17);
    lv_obj_set_y(ui_Image1, -3);
    lv_obj_set_align(ui_Image1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image2 = lv_img_create(ui_TelaInicial);
    lv_img_set_src(ui_Image2, &ui_img_clock_png);
    lv_obj_set_width(ui_Image2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image2, 68);
    lv_obj_set_y(ui_Image2, -3);
    lv_obj_set_align(ui_Image2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_btnTipoFilamento, ui_event_btnTipoFilamento, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_bStart, ui_event_bStart, LV_EVENT_ALL, NULL);
    uic_TelaInicial = ui_TelaInicial;

}
