// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

void ui_TelaRodando_screen_init(void) {
  ui_TelaRodando = lv_obj_create(NULL);
  lv_obj_clear_flag(ui_TelaRodando, LV_OBJ_FLAG_SCROLLABLE);  /// Flags

  ui_grafico = lv_chart_create(ui_TelaRodando);
  lv_obj_set_width(ui_grafico, 200);
  lv_obj_set_height(ui_grafico, 117);
  lv_obj_set_x(ui_grafico, 17);
  lv_obj_set_y(ui_grafico, -26);
  lv_obj_set_align(ui_grafico, LV_ALIGN_BOTTOM_MID);
  lv_obj_clear_flag(ui_grafico, LV_OBJ_FLAG_PRESS_LOCK);  /// Flags
  lv_chart_set_type(ui_grafico, LV_CHART_TYPE_LINE);
  lv_obj_set_style_size(ui_grafico, 0, LV_PART_INDICATOR);
  lv_chart_set_div_line_count(ui_grafico, 5, 10);
  lv_chart_set_axis_tick(ui_grafico, LV_CHART_AXIS_PRIMARY_X, 15, 8, 10, 2, false, 50);
  lv_chart_set_axis_tick(ui_grafico, LV_CHART_AXIS_PRIMARY_Y, 10, 5, 5, 2, true, 50);
  lv_chart_set_axis_tick(ui_grafico, LV_CHART_AXIS_SECONDARY_Y, 0, 0, 0, 0, false, 25);
  ui_grafico_series_sp = lv_chart_add_series(ui_grafico, lv_color_hex(0xCFDCF3), LV_CHART_AXIS_PRIMARY_Y);
  ui_grafico_series_1 = lv_chart_add_series(ui_grafico, lv_color_hex(0x808080), LV_CHART_AXIS_PRIMARY_Y);
  ui_grafico_series_2 = lv_chart_add_series(ui_grafico, lv_color_hex(0xDF180C), LV_CHART_AXIS_SECONDARY_Y);

  lv_chart_set_update_mode(ui_grafico, LV_CHART_UPDATE_MODE_SHIFT);
  lv_chart_set_point_count(ui_grafico, 30);
  lv_chart_set_range(ui_grafico, LV_CHART_AXIS_PRIMARY_Y, 15, 100);
  lv_chart_set_range(ui_grafico, LV_CHART_AXIS_SECONDARY_Y, 150, 1000);

  lv_obj_set_style_text_color(ui_grafico, lv_color_hex(0x000000), LV_PART_TICKS | LV_STATE_DEFAULT);
  lv_obj_set_style_text_opa(ui_grafico, 255, LV_PART_TICKS | LV_STATE_DEFAULT);

  ui_container = lv_obj_create(ui_TelaRodando);
  lv_obj_remove_style_all(ui_container);
  lv_obj_set_width(ui_container, 239);
  lv_obj_set_height(ui_container, 154);
  lv_obj_clear_flag(ui_container, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);  /// Flags

  ui_panelTempo = lv_obj_create(ui_container);
  lv_obj_set_width(ui_panelTempo, 238);
  lv_obj_set_height(ui_panelTempo, 50);
  lv_obj_set_x(ui_panelTempo, 1);
  lv_obj_set_y(ui_panelTempo, 1);
  lv_obj_clear_flag(ui_panelTempo, LV_OBJ_FLAG_SCROLLABLE);  /// Flags

  ui_labelTempo = lv_label_create(ui_panelTempo);
  lv_obj_set_width(ui_labelTempo, LV_SIZE_CONTENT);   /// 1
  lv_obj_set_height(ui_labelTempo, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_align(ui_labelTempo, LV_ALIGN_CENTER);
  lv_label_set_text(ui_labelTempo, "0:00");
  lv_obj_set_style_text_font(ui_labelTempo, &lv_font_montserrat_40, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_Image4 = lv_img_create(ui_panelTempo);
  lv_img_set_src(ui_Image4, &ui_img_clock_png);
  lv_obj_set_width(ui_Image4, LV_SIZE_CONTENT);   /// 1
  lv_obj_set_height(ui_Image4, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_align(ui_Image4, LV_ALIGN_RIGHT_MID);
  lv_obj_add_flag(ui_Image4, LV_OBJ_FLAG_ADV_HITTEST);   /// Flags
  lv_obj_clear_flag(ui_Image4, LV_OBJ_FLAG_SCROLLABLE);  /// Flags

  ui_barraTempo = lv_bar_create(ui_panelTempo);
  // lv_bar_set_range(ui_barraTempo, 0, 300);
  lv_bar_set_start_value(ui_barraTempo, 0, LV_ANIM_OFF);
  lv_obj_set_width(ui_barraTempo, 227);
  lv_obj_set_height(ui_barraTempo, 37);
  lv_obj_set_align(ui_barraTempo, LV_ALIGN_CENTER);
  lv_obj_set_style_radius(ui_barraTempo, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_color(ui_barraTempo, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_opa(ui_barraTempo, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

  lv_obj_set_style_radius(ui_barraTempo, 2, LV_PART_INDICATOR | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_color(ui_barraTempo, lv_color_hex(0x0E32D6), LV_PART_INDICATOR | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_opa(ui_barraTempo, 100, LV_PART_INDICATOR | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_grad_color(ui_barraTempo, lv_color_hex(0x297BDA), LV_PART_INDICATOR | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_grad_dir(ui_barraTempo, LV_GRAD_DIR_HOR, LV_PART_INDICATOR | LV_STATE_DEFAULT);

  ui_PanelTemp = lv_obj_create(ui_TelaRodando);
  lv_obj_set_width(ui_PanelTemp, 114);
  lv_obj_set_height(ui_PanelTemp, 114);
  lv_obj_set_x(ui_PanelTemp, 2);
  lv_obj_set_y(ui_PanelTemp, 54);
  lv_obj_clear_flag(ui_PanelTemp, LV_OBJ_FLAG_SCROLLABLE);  /// Flags

  ui_labelTemperatura = lv_label_create(ui_PanelTemp);
  lv_obj_set_width(ui_labelTemperatura, LV_SIZE_CONTENT);   /// 1
  lv_obj_set_height(ui_labelTemperatura, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_x(ui_labelTemperatura, -5);
  lv_obj_set_y(ui_labelTemperatura, 14);
  lv_obj_set_align(ui_labelTemperatura, LV_ALIGN_LEFT_MID);
  lv_label_set_text(ui_labelTemperatura, "55.1");
  lv_obj_set_style_text_font(ui_labelTemperatura, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_Image3 = lv_img_create(ui_PanelTemp);
  lv_img_set_src(ui_Image3, &ui_img_thermometer_png);
  lv_obj_set_width(ui_Image3, LV_SIZE_CONTENT);   /// 1
  lv_obj_set_height(ui_Image3, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_align(ui_Image3, LV_ALIGN_TOP_RIGHT);
  lv_obj_add_flag(ui_Image3, LV_OBJ_FLAG_ADV_HITTEST);   /// Flags
  lv_obj_clear_flag(ui_Image3, LV_OBJ_FLAG_SCROLLABLE);  /// Flags

  ui_PanelUmidade = lv_obj_create(ui_TelaRodando);
  lv_obj_set_width(ui_PanelUmidade, 114);
  lv_obj_set_height(ui_PanelUmidade, 114);
  lv_obj_set_x(ui_PanelUmidade, -2);
  lv_obj_set_y(ui_PanelUmidade, 54);
  lv_obj_set_align(ui_PanelUmidade, LV_ALIGN_TOP_RIGHT);
  lv_obj_clear_flag(ui_PanelUmidade, LV_OBJ_FLAG_SCROLLABLE);  /// Flags

  ui_Image5 = lv_img_create(ui_PanelUmidade);
  lv_img_set_src(ui_Image5, &ui_img_humidity_png);
  lv_obj_set_width(ui_Image5, LV_SIZE_CONTENT);   /// 1
  lv_obj_set_height(ui_Image5, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_align(ui_Image5, LV_ALIGN_TOP_RIGHT);
  lv_obj_add_flag(ui_Image5, LV_OBJ_FLAG_ADV_HITTEST);   /// Flags
  lv_obj_clear_flag(ui_Image5, LV_OBJ_FLAG_SCROLLABLE);  /// Flags

  ui_labelUmidade = lv_label_create(ui_PanelUmidade);
  lv_obj_set_width(ui_labelUmidade, LV_SIZE_CONTENT);   /// 1
  lv_obj_set_height(ui_labelUmidade, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_x(ui_labelUmidade, -5);
  lv_obj_set_y(ui_labelUmidade, 14);
  lv_obj_set_align(ui_labelUmidade, LV_ALIGN_LEFT_MID);
  lv_label_set_text(ui_labelUmidade, "15");
  lv_obj_set_style_text_font(ui_labelUmidade, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_labelMaterial = lv_label_create(ui_PanelUmidade);
  lv_obj_set_width(ui_labelMaterial, LV_SIZE_CONTENT);   /// 1
  lv_obj_set_height(ui_labelMaterial, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_x(ui_labelMaterial, 0);
  lv_obj_set_y(ui_labelMaterial, 0);
  lv_obj_set_align(ui_labelMaterial, LV_ALIGN_OUT_LEFT_TOP);
  lv_label_set_text(ui_labelMaterial, "PETG");
  lv_obj_set_style_text_font(ui_labelMaterial, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

  lv_obj_add_event_cb(ui_grafico, ui_event_grafico, LV_EVENT_ALL, NULL);
  uic_TelaRodando = ui_TelaRodando;
}
