// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////

// SCREEN: ui_TelaInicial
void ui_TelaInicial_screen_init(void);
lv_obj_t* ui_TelaInicial;
void ui_event_btnTipoFilamento(lv_event_t* e);
lv_obj_t* ui_btnTipoFilamento;
lv_obj_t* ui_labelTextoBotaoFilamento;
lv_obj_t* ui_labelTime;
lv_obj_t* ui_labelTemp;
void ui_event_bStart(lv_event_t* e);
lv_obj_t* ui_bStart;
lv_obj_t* ui_Label4;
lv_obj_t* ui_Image1;
lv_obj_t* ui_Image2;
// CUSTOM VARIABLES
lv_obj_t* uic_TelaInicial;

// SCREEN: ui_TelaRodando
void ui_TelaRodando_screen_init(void);
lv_obj_t* ui_TelaRodando;
void ui_event_grafico(lv_event_t* e);
lv_obj_t* ui_grafico;
lv_obj_t* ui_container;
lv_obj_t* ui_panelTempo;
lv_obj_t* ui_labelTempo;
lv_obj_t* ui_Image4;
lv_obj_t* ui_barraTempo;
lv_obj_t* ui_PanelTemp;
lv_obj_t* ui_labelTemperatura;
lv_obj_t* ui_Image3;
lv_obj_t* ui_PanelUmidade;
lv_obj_t* ui_Image5;
lv_obj_t* ui_labelUmidade;
// CUSTOM VARIABLES
lv_obj_t* uic_TelaRodando;

// SCREEN: ui_TelaEncerrar
void ui_TelaEncerrar_screen_init(void);
lv_obj_t* ui_TelaEncerrar;
lv_obj_t* ui_Label1;
void ui_event_Button1(lv_event_t* e);
lv_obj_t* ui_Button1;
lv_obj_t* ui_Label3;
void ui_event_Button2(lv_event_t* e);
lv_obj_t* ui_Button2;
lv_obj_t* ui_Label2;
// CUSTOM VARIABLES
lv_obj_t* uic_TelaEncerrar;

// EVENTS
lv_obj_t* ui____initial_actions0;

// IMAGES AND IMAGE SETS

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
#error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP != 1
#error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_btnTipoFilamento(lv_event_t* e) {
  lv_event_code_t event_code = lv_event_get_code(e);

  if (event_code == LV_EVENT_CLICKED) {
    btnMudarFilamentoClick(e);
  }
}

void ui_event_bStart(lv_event_t* e) {
  lv_event_code_t event_code = lv_event_get_code(e);

  if (event_code == LV_EVENT_CLICKED) {
    _ui_screen_change(&ui_TelaRodando, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_TelaRodando_screen_init);
  }
}

void ui_event_grafico(lv_event_t* e) {
  lv_event_code_t event_code = lv_event_get_code(e);

  if (event_code == LV_EVENT_CLICKED) {
    _ui_screen_change(&ui_TelaEncerrar, LV_SCR_LOAD_ANIM_OUT_TOP, 500, 0, &ui_TelaEncerrar_screen_init);
  }
}

void ui_event_Button1(lv_event_t* e) {
  lv_event_code_t event_code = lv_event_get_code(e);

  if (event_code == LV_EVENT_CLICKED) {
    _ui_screen_change(&ui_TelaInicial, LV_SCR_LOAD_ANIM_NONE, 500, 0, &ui_TelaInicial_screen_init);
    btnVoltarTelainicialClick(e);
  }
}

void ui_event_Button2(lv_event_t* e) {
  lv_event_code_t event_code = lv_event_get_code(e);

  if (event_code == LV_EVENT_CLICKED) {
    _ui_screen_change(&ui_TelaRodando, LV_SCR_LOAD_ANIM_NONE, 500, 0, &ui_TelaRodando_screen_init);
  }
}

///////////////////// SCREENS ////////////////////

void ui_init(void) {
  lv_disp_t* dispp = lv_disp_get_default();
  lv_theme_t* theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED), false, LV_FONT_DEFAULT);
  lv_disp_set_theme(dispp, theme);
  ui_TelaInicial_screen_init();
  ui_TelaRodando_screen_init();
  ui_TelaEncerrar_screen_init();
  ui____initial_actions0 = lv_obj_create(NULL);
  lv_disp_load_scr(ui_TelaInicial);
}
