// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"
#include "ui_events.h"
#include "ui_helpers.h"

// SCREEN: ui_TelaInicial
void ui_TelaInicial_screen_init(void);
extern lv_obj_t* ui_TelaInicial;
void ui_event_btnTipoFilamento(lv_event_t* e);
extern lv_obj_t* ui_btnTipoFilamento;
extern lv_obj_t* ui_labelTextoBotaoFilamento;
extern lv_obj_t* ui_labelTime;
extern lv_obj_t* ui_labelTemp;
void ui_event_bStart(lv_event_t* e);
extern lv_obj_t* ui_bStart;
extern lv_obj_t* ui_Label4;
extern lv_obj_t* ui_Image1;
extern lv_obj_t* ui_Image2;
// CUSTOM VARIABLES
extern lv_obj_t* uic_TelaInicial;

// SCREEN: ui_TelaRodando
void ui_TelaRodando_screen_init(void);
extern lv_obj_t* ui_TelaRodando;
void ui_event_grafico(lv_event_t* e);
extern lv_obj_t* ui_grafico;
extern lv_obj_t* ui_container;
extern lv_obj_t* ui_panelTempo;
extern lv_obj_t* ui_labelTempo;
extern lv_obj_t* ui_Image4;
extern lv_obj_t* ui_barraTempo;
extern lv_obj_t* ui_PanelTemp;
extern lv_obj_t* ui_labelTemperatura;
extern lv_obj_t* ui_Image3;
extern lv_obj_t* ui_PanelUmidade;
extern lv_obj_t* ui_Image5;
extern lv_obj_t* ui_labelUmidade;
// CUSTOM VARIABLES
extern lv_obj_t* uic_TelaRodando;

// SCREEN: ui_TelaEncerrar
void ui_TelaEncerrar_screen_init(void);
extern lv_obj_t* ui_TelaEncerrar;
extern lv_obj_t* ui_Label1;
void ui_event_Button1(lv_event_t* e);
extern lv_obj_t* ui_Button1;
extern lv_obj_t* ui_Label3;
void ui_event_Button2(lv_event_t* e);
extern lv_obj_t* ui_Button2;
extern lv_obj_t* ui_Label2;
// CUSTOM VARIABLES
extern lv_obj_t* uic_TelaEncerrar;

// EVENTS

extern lv_obj_t* ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_thermometer_png);  // assets/thermometer.png
LV_IMG_DECLARE(ui_img_clock_png);        // assets/clock.png
LV_IMG_DECLARE(ui_img_humidity_png);     // assets/humidity.png

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
