// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void btnFilamentChangeClick(lv_event_t* e);
void btnBackToStartScreenClick();
void btnEndAlertClick(lv_event_t* e);
void btnStartClick();
void clickChart();
void playButtonTone();

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
